import React from 'react';
import {
  Lightbulb,
  CheckCircle2,
  XCircle,
  HelpCircle,
  PlayCircle,
  ArrowRight,
  TrendingDown,
  TrendingUp,
  Clock,
  Layers,
  Sparkles,
  ShieldCheck
} from 'lucide-react';
import { useWorkforce } from '../context/WorkforceContext';
import { Recommendation } from '../types';

export const Recommendations: React.FC = () => {
  const {
    recommendations,
    approveRecommendation,
    dismissRecommendation,
    openExplainabilityModal,
    setActiveTab,
    applySimulationScenario
  } = useWorkforce();

  const handleSimulate = (rec: Recommendation) => {
    applySimulationScenario('A');
    setActiveTab('workload');
  };

  return (
    <div className="space-y-6">
      {/* Top Banner */}
      <div className="bg-white rounded-xl border border-slate-200 shadow-card p-5">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2">
              <span className="p-1.5 rounded-lg bg-brand-50 text-brand-600 border border-brand-200">
                <Lightbulb className="w-4 h-4" />
              </span>
              <h2 className="text-base font-bold text-slate-900 tracking-tight">AI Workload Optimization Plan</h2>
              <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-brand-100 text-brand-800 uppercase">
                Human-in-the-Loop Required
              </span>
            </div>
            <p className="text-xs text-slate-500 mt-1 max-w-2xl leading-relaxed">
              Recommended operational actions generated by constraint optimization algorithms to resolve workload saturation and restore healthy delivery velocity.
            </p>
          </div>

          <div className="text-right">
            <span className="text-xs font-semibold text-slate-400 block">Pending Approvals</span>
            <span className="text-2xl font-black text-brand-700 font-sans">
              {recommendations.filter(r => r.status === 'pending').length} / {recommendations.length}
            </span>
          </div>
        </div>
      </div>

      {/* Recommendations List */}
      <div className="space-y-4">
        {recommendations.map(rec => {
          const isApproved = rec.status === 'approved';
          const isDismissed = rec.status === 'dismissed';

          return (
            <div
              key={rec.id}
              className={`bg-white rounded-xl border p-5 shadow-card transition-all ${
                isApproved
                  ? 'border-emerald-200 ring-1 ring-emerald-100 bg-emerald-50/20'
                  : isDismissed
                  ? 'border-slate-200 opacity-60 bg-slate-50/50'
                  : 'border-slate-200 hover:border-slate-300'
              }`}
            >
              <div className="flex flex-col lg:flex-row items-start justify-between gap-4">
                {/* Left: Number + Details */}
                <div className="flex items-start gap-3.5 flex-1">
                  <div
                    className={`w-8 h-8 rounded-xl font-bold text-sm flex items-center justify-center shrink-0 shadow-sm ${
                      isApproved
                        ? 'bg-emerald-600 text-white'
                        : isDismissed
                        ? 'bg-slate-300 text-slate-700'
                        : 'bg-brand-600 text-white'
                    }`}
                  >
                    {rec.number}
                  </div>

                  <div className="space-y-2">
                    <div className="flex flex-wrap items-center gap-2">
                      <span className="text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded bg-slate-100 text-slate-700 border border-slate-200">
                        {rec.category}
                      </span>
                      <span className="text-[10px] font-semibold text-slate-400">
                        Confidence: <strong className="text-slate-800">{rec.confidence}%</strong>
                      </span>
                      <span className={`text-[10px] font-bold px-2 py-0.5 rounded border uppercase ${
                        rec.risk === 'Low' ? 'bg-emerald-50 text-emerald-700 border-emerald-200' :
                        rec.risk === 'Medium' ? 'bg-amber-50 text-amber-700 border-amber-200' :
                        'bg-red-50 text-red-700 border-red-200'
                      }`}>
                        {rec.risk} Implementation Risk
                      </span>

                      {isApproved && (
                        <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-emerald-100 text-emerald-800 border border-emerald-200 flex items-center gap-1 uppercase">
                          <CheckCircle2 className="w-3 h-3 text-emerald-600" />
                          Plan Approved & Active
                        </span>
                      )}
                    </div>

                    <h3 className="text-sm font-bold text-slate-900 tracking-tight leading-snug">
                      {rec.title}
                    </h3>
                    <p className="text-xs text-slate-600 leading-relaxed">
                      {rec.reason}
                    </p>

                    {/* Affected Teams */}
                    <div className="flex flex-wrap items-center gap-2 pt-1">
                      <span className="text-[10px] font-bold uppercase text-slate-400">Affected Teams:</span>
                      {rec.affectedTeams.map(t => (
                        <span key={t} className="text-[11px] font-semibold text-slate-700 bg-slate-100 px-2 py-0.5 rounded">
                          {t}
                        </span>
                      ))}
                    </div>
                  </div>
                </div>

                {/* Right: Projected Impact Cards */}
                <div className="w-full lg:w-72 shrink-0 bg-slate-50 p-3 rounded-xl border border-slate-200/80">
                  <div className="text-[10px] font-bold uppercase tracking-wider text-slate-500 mb-2">
                    Projected Operational Impact:
                  </div>
                  <div className="grid grid-cols-2 gap-2 text-xs">
                    <div className="p-2 rounded bg-white border border-slate-100">
                      <span className="text-[10px] text-slate-400 block font-semibold">Capacity</span>
                      <span className="font-bold text-slate-900">
                        {rec.expectedImpact.capacityBefore}% → {rec.expectedImpact.capacityAfter}%
                      </span>
                    </div>
                    <div className="p-2 rounded bg-white border border-slate-100">
                      <span className="text-[10px] text-slate-400 block font-semibold">Overtime</span>
                      <span className="font-bold text-emerald-600">
                        {rec.expectedImpact.overtimeDeltaPct}%
                      </span>
                    </div>
                    <div className="p-2 rounded bg-white border border-slate-100">
                      <span className="text-[10px] text-slate-400 block font-semibold">Deadline Risk</span>
                      <span className="font-bold text-emerald-600">
                        {rec.expectedImpact.deadlineRiskDeltaPct}%
                      </span>
                    </div>
                    <div className="p-2 rounded bg-white border border-slate-100">
                      <span className="text-[10px] text-slate-400 block font-semibold">Productivity</span>
                      <span className="font-bold text-emerald-600">
                        +{rec.expectedImpact.productivityDeltaPct}%
                      </span>
                    </div>
                  </div>
                </div>
              </div>

              {/* Bottom Actions Toolbar */}
              <div className="mt-4 pt-3 border-t border-slate-100 flex flex-wrap items-center justify-between gap-3">
                <button
                  onClick={() => openExplainabilityModal(rec)}
                  className="text-xs font-semibold text-brand-600 hover:text-brand-800 flex items-center gap-1.5"
                >
                  <HelpCircle className="w-3.5 h-3.5" />
                  <span>Why this recommendation? (Explain Model Reasoning)</span>
                </button>

                {!isApproved && !isDismissed && (
                  <div className="flex items-center gap-2">
                    <button
                      onClick={() => dismissRecommendation(rec.id)}
                      className="px-3 py-1.5 rounded-lg border border-slate-300 text-slate-600 hover:bg-slate-50 text-xs font-semibold transition-colors"
                    >
                      Dismiss
                    </button>
                    <button
                      onClick={() => handleSimulate(rec)}
                      className="px-3.5 py-1.5 rounded-lg border border-brand-300 text-brand-700 bg-brand-50 hover:bg-brand-100 text-xs font-bold transition-colors flex items-center gap-1.5"
                    >
                      <PlayCircle className="w-3.5 h-3.5" />
                      <span>Simulate in Planner</span>
                    </button>
                    <button
                      onClick={() => approveRecommendation(rec.id)}
                      className="px-4 py-1.5 rounded-lg bg-brand-600 hover:bg-brand-700 text-white text-xs font-bold shadow-sm transition-colors flex items-center gap-1.5"
                    >
                      <CheckCircle2 className="w-3.5 h-3.5" />
                      <span>Approve Plan</span>
                    </button>
                  </div>
                )}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};
